# Generated by Django 2.0.6 on 2018-06-16 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cycle', models.CharField(choices=[('Cycle 3', 'Cycle 3'), ('Cycle 4', 'Cycle 4')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=5, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('cycle', models.CharField(choices=[('Cycle 3', 'Cycle 3'), ('Cycle 4', 'Cycle 4')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.CharField(choices=[('Cycle 3', 'Cycle 3'), ('Cycle 4', 'Cycle 4')], max_length=7),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Classe'),
        ),
        migrations.AddField(
            model_name='competence',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Domaine'),
        ),
    ]
