# Generated by Django 2.0.6 on 2018-07-04 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0017_auto_20180704_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumResultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnumTrimestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('competence', models.ManyToManyField(to='gestion.Competence')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.EnumCycle')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultat.EnumTrimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Competence')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Eleve')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultat.Evaluation')),
                ('resultat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultat.EnumResultat')),
            ],
        ),
    ]
