# Generated by Django 2.0.6 on 2018-07-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enumtrimestre',
            name='literal',
            field=models.CharField(max_length=11),
        ),
    ]
