# Generated by Django 2.0.6 on 2018-06-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20180616_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='ref',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='ref',
            field=models.CharField(max_length=10),
        ),
    ]
