# Generated by Django 2.0.6 on 2018-06-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_domaine_sousdomaine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domaine',
            old_name='sousDomaine',
            new_name='sous_domaine',
        ),
    ]
