# Generated by Django 2.0.6 on 2018-06-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_eleve_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestion.Classe'),
        ),
    ]
