# Generated by Django 2.0.6 on 2018-06-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_competence_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='domaine',
            field=models.ForeignKey(blank=True, default=-1, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Domaine'),
        ),
    ]
