# Generated by Django 2.0.6 on 2018-06-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_competence_domaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='ref',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='ref',
            field=models.CharField(max_length=5),
        ),
    ]
