# Generated by Django 2.0.6 on 2018-07-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20180627_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=10)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.EnumCycle'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.EnumCycle'),
        ),
        migrations.AlterField(
            model_name='competence',
            name='domaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Domaine'),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.EnumCycle'),
        ),
        migrations.AlterField(
            model_name='domaine',
            name='sous_domaine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Domaine'),
        ),
    ]
